projects:
  - id: auto-deal-eth
    name: Auto Deal ETH
    script_path: '/Users/mac/frontend/code/1.operations/auto-deal-eth'
    venv_path: "venv"
    scripts:
      - id: run-calendar
        name: Calendar Runner
        icon: "🛰"
        run: "python -m getinfo.run_calendar"
        schedule:
          mode: interval
          seconds: 6000000
      - id: run-1
        name: Runner 1
        icon: "🔎"
        run: "python -m getinfo.run_binance_square"
        schedule:
          mode: once
          enabled: false
